### PR TITLE
closes #11 - Kilo (Remapping to controller)

### LINKED ISSUE #11: Kilo - Remapping to a controller
- This will be routing rule, using an existing controller
- Make the target link /show/2
- There is no Show controller, but we have a show method in our base controller. We want to remap these requests to Welcome::show(), so they work as intended

$route['show/(:any)'] = 'welcome/show/$1';

### PR DESCRIPTION
**Pull request by btraas**

### CODE REVIEW

**Review by ConnorJang — CHANGES_REQUESTED** [review]
Please resolve the merge conflicts

**Comment by btraas** [comment]
Fixed. Please merge

**Review by ConnorJang — CHANGES_REQUESTED** [review]
please change the config so that the navbar link works

**Comment by btraas** [comment]
Added link in nav for Kilo, Merged Clint's Delta commit.

**Pull request merged**
